<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->insert([
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 1,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問１の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 2,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問2の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 3,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問3の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 4,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問4の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 5,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問5の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 6,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問6の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 7,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問7の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 8,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問8の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 9,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問9の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 10,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問10の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 11,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問1１の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 12,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問12の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 13,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問13の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 14,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問14の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 15,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問15の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 16,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問16の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 17,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問17の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 18,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問18の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 19,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問19の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 20,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問20の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 21,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問2１の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 22,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問22の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 23,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問23の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 24,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問24の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 25,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問25の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 26,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問26の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 27,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問27の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 28,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問28の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 29,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問29の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 30,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問30の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 31,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問3１の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 32,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問32の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 33,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問33の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 34,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問34の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 35,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問35の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 36,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問36の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 37,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問37の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 38,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問38の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 39,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問39の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 40,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問40の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 41,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問4１の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 42,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問42の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 43,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問43の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 44,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問44の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 45,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問45の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 46,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問46の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 47,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問47の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 48,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問48の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 49,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問49の解説です。',
            ],
            [
                'subject_id' => 1,
                'year_id' => 1,
                'form_id' => 1,
                'question_number' => 50,
                'answer' => 'ア：XXXXXXX',
                'explanation' => '２０２２年度・フォームA・生命保険総論・問50の解説です。',
            ],
        ]);
    }
}
